### ISSUE TITLE
Vanilla Recipe Conflicts

### ISSUE THREAD

**Issue by dannydjdk** [CiFru/AdditionalBlocksStoneEdition#1]
Version: 1.1.9-mc1.16

Andesite, Diorite and Granite bricks have the same recipe as the vanilla Polished version of these blocks.
Perhaps a better alternative would be to have them crafted with the polished blocks.

**Comment by CiFru** [comment]
I wasn't aware of that, I'll make sure to patch it in the next update. Thanks for pointing it out.
