### ISSUE TITLE
Mod Update request

### ISSUE THREAD

**Issue by GalaxyOfZero** [CiFru/AdditionalBlocksStoneEdition#10]
The Mod abstoneedition needs a Update for the SuperMartijn642's Config Lib to the version 1.1.6, i have troble to start it with the new version of the SuperMartijn642's Config Lib, in my Pack i use tow other mods did need the same Config Lib and its not good if a can not Update this mods

[crash-2022-08-02_10.52.02-fml.txt](https://github.com/CiFru/AdditionalBlocksStoneEdition/files/9240653/crash-2022-08-02_10.52.02-fml.txt)

**Comment by CiFru** [comment]
It's fixed in the latest version (2.0.8)
