### ISSUE TITLE
Recipe Yield Question/Request

### ISSUE THREAD

**Issue by dannydjdk** [CiFru/AdditionalBlocksStoneEdition#2]
While some of the recipes yield the same number of blocks as the input, some of them don't. For instance, 9 vanilla stone blocks are required to make 4 Stone Brick Blocks. This is also true for Bloodstone Block and further for the Bloodstone Brick (5 obsidian + 4 redstone crafts down to 2 Bloodstone Brick blocks). Similarly, the path blocks and charred logs require more blocks than they yield.

Is this by design? If so, I'll just change it in my own pack. However, given that these are decorative blocks, I think it would be reasonable to allow a 1:1 ratio of input to output blocks unless there is some other reason for the added expense that I'm not aware of.

**Comment by CiFru** [comment]
Most of these are by design, but I can imagine that it's rough to grind for these blocks in survival for example. I'll revisit the recipes and probably make some changes here and there.

**Comment by CiFru** [comment]
I've uploaded the new version, where I've changed most of the yields of the recipes. I've also patched the issue of overlapping recipes, so I'll close these issues.
