### ISSUE TITLE
New ingots/ores

### ISSUE THREAD

**Issue by celsiusqc** [CiFru/AdditionalBlocksStoneEdition#3]
Please use the forge ore and ingot dictionary instead of your own for recipes. This will make it so I can use create copper ingot in your recipes.

**Comment by celsiusqc** [comment]
> Please use the forge ore and ingot dictionary instead of your own for recipes. This will make it so I can use create copper ingot in your recipes.

also, please add to the config a disable for the copper and silver tools so they do not show in jei like you did very well for the ores and stones. :)

**Comment by CiFru** [comment]
I've just added all of my items and blocks to the forge tags, and fixed the config option for the tools. Everything should be patched in the next update.
