### ISSUE TITLE
bloodstone

### ISSUE THREAD

**Issue by celsiusqc** [CiFru/AdditionalBlocksStoneEdition#4]
Please consider adding the recipe for bloodstone to accept coal blocks AND charcoal blocks

**Comment by CiFru** [comment]
Are you perhaps referring to my "charred wood" block? The textures don't really match so that'd be kinda odd. If not, charcoal blocks don't seem to exist in vanilla, so I'm probably not going to add the feature. I appreciate the comment though :)
