### ISSUE TITLE
Disabling copper/silver/marble in the config doesn't disable the worldgen

### ISSUE THREAD

**Issue by enduum** [CiFru/AdditionalBlocksStoneEdition#5]
Disabling any other block in the config works as you would expect, disabling the recipes and hiding the blocks from JEI and the creative menu.
Disabling copper or silver also results in disabled recipes/hidden blocks, but marble as well as copper and silver ores still generate in the world. The ores can be smelted into ingots and used to make tools/blocks/nuggets, but marble cannot be used to craft anything at all.

Minecraft 1.16.5
Forge 36.1.18
Additional Blocks Stone Edition 2.0.1
SuperMartijn642's Config Lib 1.0.5a
Tested on a clean instance with no other mods

**Comment by CiFru** [comment]
Thanks for the info, I'll be patching the issue in the next update.

**Comment by CiFru** [comment]
I've just uploaded a new version of my mod. The issue should be patched in this version.
