### ISSUE TITLE
unable to start the game with mac

### ISSUE THREAD

**Issue by ink717** [CiFru/AdditionalBlocksStoneEdition#7]
the newest version (actually including a couple of previous versions as well) of the mod can't launch the game due to a Java Language error. Tried different java, forge versions, not work.
However, the windows will work fine.

**Comment by CiFru** [comment]
I don't have a mac or any other apple pc, so I'm not sure if I'll be able to fix this one. Do you know which piece of code is causing a problem, or can you share a crash report?

**Comment by ink717** [comment]
[latest.log](https://github.com/CiFru/AdditionalBlocksStoneEdition/files/6489808/latest.log)
[crash-2021-05-16_13.03.txt](https://github.com/CiFru/AdditionalBlocksStoneEdition/files/6489809/crash-2021-05-16_13.03.txt)

**Comment by SuperMartijn642** [comment]
@ink717 Could you see if [this version](https://drive.google.com/file/d/1p4FAGi4eGQJr14YtVNPaSav_CzD4f1lZ/view?usp=sharing) of Config Lib fixes the problem?
Just make sure to disable to current config lib version when you use this one.

**Comment by ink717** [comment]
unfortunately it didn't work

**Comment by SuperMartijn642** [comment]
Could you share the new log files?

**Comment by CiFru** [comment]
I'm closing this issue due to no response
