### ISSUE TITLE
Blocks do not have tools assigned for breaking

### ISSUE THREAD

**Issue by TOLoneWolf** [CiFru/AdditionalBlocksStoneEdition#9]
abstoneedition-2.0.7-mc1.17

There is no tools assigned to break any of the blocks so they break at hand speed and also can be broken by hand and still get the blocks back.

They should break with the proper tools for the type of material they are.
pickaxe for stone based blocks.
axe for wood based like the charred log.

Very nice addition, love the textures.

**Comment by CiFru** [comment]
Heyo, which forge version are you using?

**Comment by TOLoneWolf** [comment]
it was ether 1.17.1-37.0.67 or 37.0.53.

**Comment by CiFru** [comment]
It's been fixed in the latest version (2.0.8), sorry for the long wait
